name: CI/CD

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build-and-test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        node-version: [18.x, 20.x]
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Build TypeScript
      run: npm run build
    
    - name: Check for build artifacts
      shell: bash
      run: |
        if [ ! -d "dist" ]; then
          echo "Error: dist directory not created"
          exit 1
        fi
        if [ ! -f "dist/main.js" ]; then
          echo "Error: main.js not compiled"
          exit 1
        fi
        echo "Build artifacts verified successfully"
    
    - name: Lint TypeScript (if configured)
      continue-on-error: true
      run: npm run lint || echo "No lint script configured"
    
    - name: Package application (Ubuntu only)
      if: matrix.os == 'ubuntu-latest' && matrix.node-version == '20.x'
      run: |
        npm install --save-dev @electron-forge/cli @electron-forge/maker-squirrel @electron-forge/maker-zip @electron-forge/maker-deb @electron-forge/maker-rpm
        npx electron-forge import || echo "Forge config already exists"
        npm run package || echo "Package script not configured yet"
    
    - name: Test Electron startup (headless)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb
        xvfb-run --auto-servernum --server-args="-screen 0 1280x1024x24" npm start &
        sleep 5
        pkill -f electron || echo "Electron process check completed"

  code-quality:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Check TypeScript compilation
      run: npx tsc --noEmit
    
    - name: Check for security vulnerabilities
      run: npm audit --audit-level=moderate || echo "Security audit completed with warnings"
    
    - name: Check package.json validity
      run: node -e "require('./package.json')"

  notify-status:
    needs: [build-and-test, code-quality]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
    - name: Build Status
      run: |
        if [ "${{ needs.build-and-test.result }}" == "success" ] && [ "${{ needs.code-quality.result }}" == "success" ]; then
          echo "✅ All checks passed!"
        else
          echo "❌ Some checks failed"
          exit 1
        fi

